export {default as Header} from './header/header'
export {default as Footer} from './footer/footer'
export {default as Button} from './button/button'
export {default as PhotoFrame} from './photoFrame/photoFrame'
export {default as Divider} from './divider/divider'
export {default as TextInput} from './textInput/textInput'
export {default as TextArea} from './textArea/textArea'
export {default as NavSlider} from './navSlider/navSlider'
export {default as OptImage} from './image/optimizedImage'

